// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EntityFramework.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    [Migration("20190521041747_Migracion")]
    partial class Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EntityFramework.ClasesEntidad.Tarea", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("FechaDeCreacion");

                    b.Property<DateTime>("FechaVencimiento");

                    b.Property<bool>("Finalizada");

                    b.Property<DateTime>("UltimaActualizacion");

                    b.Property<int>("UsuarioRefId");

                    b.HasKey("Codigo");

                    b.HasIndex("UsuarioRefId");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("EntityFramework.ClasesEntidad.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Correo");

                    b.Property<string>("Identificacion")
                        .IsRequired();

                    b.Property<string>("Nombre");

                    b.Property<string>("Password");

                    b.Property<string>("User");

                    b.HasKey("Codigo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("EntityFramework.ClasesEntidad.Tarea", b =>
                {
                    b.HasOne("EntityFramework.ClasesEntidad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioRefId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
